
services:
  mongodb:
    image: mongo:7
    container_name: dsa-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dsa-network

  dsa-app:
    build: .
    container_name: dsa-cli
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/dsa?authSource=admin
    networks:
      - dsa-network
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  mongodb_data:

networks:
  dsa-network:
    driver: bridge